/* DO NOT TOUCH, AUTOGENERATED BY OFFSET.C */

#ifndef _MIPS_OFFSET_H
#define _MIPS_OFFSET_H

/* MIPS pt_regs offsets. */
#define PT_R0     32
#define PT_R1     48
#define PT_R2     64
#define PT_R3     80
#define PT_R4     96
#define PT_R5     112
#define PT_R6     128
#define PT_R7     144
#define PT_R8     160
#define PT_R9     176
#define PT_R10    192
#define PT_R11    208
#define PT_R12    224
#define PT_R13    240
#define PT_R14    256
#define PT_R15    272
#define PT_R16    288
#define PT_R17    304
#define PT_R18    320
#define PT_R19    336
#define PT_R20    352
#define PT_R21    368
#define PT_R22    384
#define PT_R23    400
#define PT_R24    416
#define PT_R25    432
#define PT_R26    448
#define PT_R27    464
#define PT_R28    480
#define PT_R29    496
#define PT_R30    512
#define PT_R31    528
#define PT_LO     544
#define PT_HI     560
#define PT_EPC    580
#define PT_BVADDR 584
#define PT_STATUS 588
#define PT_CAUSE  592
#define PT_SIZE   608

/* MIPS task_struct offsets. */
#define TASK_STATE         0
#define TASK_FLAGS         4
#define TASK_SIGPENDING    8
#define TASK_NEED_RESCHED  20
#define TASK_COUNTER       24
#define TASK_PRIORITY      28
#define TASK_MM            1080

/* MIPS specific thread_struct offsets. */
#define THREAD_REG16   576
#define THREAD_REG17   592
#define THREAD_REG18   608
#define THREAD_REG19   624
#define THREAD_REG20   640
#define THREAD_REG21   656
#define THREAD_REG22   672
#define THREAD_REG23   688
#define THREAD_REG29   704
#define THREAD_REG30   720
#define THREAD_REG31   736
#define THREAD_STATUS  752
#define THREAD_FPU     760
#define THREAD_BVADDR  1024
#define THREAD_BUADDR  1028
#define THREAD_ECODE   1032
#define THREAD_TRAPNO  1036
#define THREAD_PGDIR   1040
#define THREAD_MFLAGS  1044
#define THREAD_CURDS   1048
#define THREAD_TRAMP   1052
#define THREAD_OLDCTX  1056

/* Linux mm_struct offsets. */
#define MM_COUNT      16
#define MM_PGD        12
#define MM_CONTEXT    36

/* Linux sigcontext offsets. */
#define SC_REGMASK    0
#define SC_STATUS     4
#define SC_PC         8
#define SC_REGS       16
#define SC_FPREGS     528
#define SC_OWNEDFP    784
#define SC_FPC_CSR    788
#define SC_FPC_EIR    792
#define SC_SSFLAGS    796
#define SC_MDHI       800
#define SC_MDLO       816
#define SC_CAUSE      840
#define SC_BADVADDR   844
#define SC_SIGSET     848

#endif /* !(_MIPS_OFFSET_H) */
