/* DO NOT TOUCH, AUTOGENERATED BY R5900_OFFSET.C */

#ifndef _MIPS_R5900_OFFSET_H
#define _MIPS_R5900_OFFSET_H

/* r5900 pt_regs offsets. */
#define PT_SA      576

/* r5900 sigcontext offsets. */
#define SC_SA          832
#define SC_FP_ACC      836

/* r5900 specific thread_struct offsets. */
#define THREAD_FPU_ACC   1020

/* r5900  r5900_upper_ctrs offsets. */
#define UPPER_CTRS_CTR0   0
#define UPPER_CTRS_CTR1   4
#define UPPER_CTRS_SIZE   8

/* r5900  perf_sample_entry offsets. */
#define PERF_ENTRY_PC      0
#define PERF_ENTRY_PID     4
#define PERF_ENTRY_EVENT   8
#define PERF_ENTRY_CID     10
#define PERF_ENTRY_JIFFIES 12
#define PERF_ENTRY_SIZE    20
#define SIZEOF_JIFFIES     4

/* r5900 ctrset_struct offsets. */
#define CTRPAIR_CUR0      12
#define CTRPAIR_CUR1      16
#define CTRPAIR_VAL0      4
#define CTRPAIR_VAL1      8
#define CTRPAIR_EV0       0
#define CTRPAIR_EV1       1
#define CTRPAIR_SIZE      20

/* r5900  pc_record offsets. */
#define PC_RECORD_DEBUG_BASE 0
#define PC_RECORD_DEBUG_PTR 4
#define PC_RECORD_POOL_IN 8
#define PC_RECORD_POOL_OUT 12
#define PC_RECORD_POOL_NUM 16
#define PC_RECORD_LOST    24
#define PC_RECORD_MAX_ENTRY 20
#define PC_RECORD_P0BUFFER  144
#define PC_RECORD_P0NUMENT  140
#define PC_RECORD_RELOAD0 28
#define PC_RECORD_RELOAD1 32
#define PC_RECORD_MODE    36
#define PC_RECORD_CUR_NUM 48
#define PC_RECORD_CUR_PAIR  52
#define PC_RECORD_INIT_PAIR 56
#define PC_RECORD_NUM_PAIR  44
#define PC_RECORD_REG_A0  64
#define PC_RECORD_REG_A1  80
#define PC_RECORD_REG_A2  96
#define PC_RECORD_NUM_IPID 112
#define PC_RECORD_IGNORE   116
#define PC_RECORD_IPID     120
#define PC_RECORD_SIZE    1168
#define PC_BUFFDESCR_SIZE    8

/* r5900 task_struct offsets. */
#define TASK_PID         92
#define SIZEOF_PID       4

#endif /* !(_MIPS_R5900_OFFSET_H) */
